# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: owi
email: june3121@163.com
description: lonely kid hides in heart 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.owi.icu" # the base hostname & protocol for your site
github_username:  June-Alice
paginate: 5
theme-dark: false #Set to true to change to dark website theme
#intensedebate_comments评论服务
intensedebate_comments: true
plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
